### ISSUE TITLE
Shouldn't map() run the callback in parallel?

### ISSUE THREAD

**Issue by andywer** [developit/asyncro#1]
Hi @developit. I had a quick look on your lib, but something seemed rather strange to me.

Why does `map()` run the callback serially? The nice thing about `map` is that it provides great opportunities for concurrent processing.

Let's say I do `map(['/a', '/b', '/c'], async (item) => await fetch(item))` and every fetch takes 100ms. I would expect the `map()` to resolve after 100ms, not 300 ms.

Doing `filter()` and `reduce()` concurrently might get tricky, but `map()` should be rather carefree :)

Cheers

**Comment by andywer** [comment]
True, but I fear that might make usage rather uncomfortable.

I'm just concerned about the potential performance impact.
Wondering how other people think about this...

**Comment by TuckerWhitehouse** [comment]
I was just going to pull this into a project to replace a line similar to the following, so glad to know that it would not be running them in parallel as expected.
```javascript
await Promise.all(arr.map(async (item) => { ... some async stuff ... }))
```

**Comment by developit** [comment]
Sounds like we need parallel versions of these methods.  I think for `map()` in particular parallel could just be the default. `reduce()` is more problematic since it can be used in a variety of different ways, some of which are order-sensitive.

**Comment by developit** [comment]
`map()` and `filter()` are now parallel by default, thanks guys! 🙌

**Comment by developit** [comment]
Released as [2.0.0](https://github.com/developit/asyncro/releases/tag/2.0.0).

**Comment by andywer** [comment]
True. But I fear that might make usage rather uncomfortable...

Problem is the potential performance impact :-/

**Comment by developit** [comment]
@andywer already worked around it ;)

**Comment by andywer** [comment]
@developit Lol. I sent this reply via email last weekend when github was down. I wonder what it was doing in the meantime ^^
