### ISSUE TITLE
Series is executing in parallel

### ISSUE THREAD

**Issue by TuckerWhitehouse** [developit/asyncro#3]
From what I can tell, the `series` method is actually executing all of the methods when it's called, and then waiting for each one to resolve in series before adding it to the array. I think the expected behavior would be that each method is not called until the previous one has resolved.

```
series([1,2,3,4].map((n) => {
  return async () => new Promise((resolve) => {
    console.log(n)
    setTimeout(() => resolve(n), 1000)
  })
}))
```

*Expected:* Each number is logged out 1 second after the previous, total runtime is ~4 seconds
*Actual:* All numbers are printed immediately, total runtime is ~1 second

I think one way of solving this would be to remove https://github.com/developit/asyncro/blob/master/src/util.js#L6
And change https://github.com/developit/asyncro/blob/master/src/util.js#L6 to be
`acc.push(await v());`, but I'm not sure if that's the best way.
** This would break the `parallel` method, so no go there

**Comment by developit** [comment]
Hmm, interesting.  Actually that seems to be how [series() used to work](https://github.com/developit/asyncro/commit/27ec488d7fa1e352f0b9604aa021334b0335281b#diff-1fdf421c05c1140f6d71444ea2b27638R96).  I don't recall why it was changed.
