### ISSUE TITLE
Next version plan?

### ISSUE THREAD

**Issue by fimars** [developit/asyncro#7]
Awesome, `asyncro` is both simple and practical.

Some suggestions:
 - support more `Array` operators. In fact, most operators are the same pattern like `filter`. 
 - support `Object`, maybe like `lodash.js`.

If you have any plan, very happy to make a PR. 🐵

**Comment by developit** [comment]
Would definitely like to support `filter()`! It'd be easy to slot into the current library.

I haven't thought much about Objects for this library, since there aren't really any built-ins.  Normally for object iteration I drop out of Functional Programming and use `in` loops.
